const CartActionType ={
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    DECREASE_QUANTITY: 'DECREASE_QUANTITY',
    REMOVE_ITEM:'REMOVE_ITEM'
}

export default CartActionType;